[package]
name = "wxml_parser"
version = "0.1.0"
authors = ["yisar <1533540012@qq.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/yisar/wxml"
documentation = "https://github.com/yisar/wxml"
homepage = "https://crates.io/crates/wxml"
description = """
wxml parser
"""
keywords = ["wxmlparser"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"